pipeline {
    agent any
    stages{
        
        stage('mostrarFecha') {
            steps {
                script{
                    def dia = new Date()
                    println("Chocolate Blanco			   1000
Chocolate Negro              1500
Chocolate con almendras		1200
Chocolate en rama			100
                }
            }
        }
            
    }
}