pipeline {
    agent any
    stages{
        
        stage('mostrarFecha') {
            steps {
                script{
                    def dia = new Date()
                    println("Chocolate Blanco			  1000")
                    println("Chocolate Negro              1500")    
                    println("Chocolate con almendras      1200")
                    println("Chocolate en rama            100")
                }
            }
        }
            
    }
}
